# -*- coding: utf-8 -*-
"""suburbsid_suburbsname.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15iiOATnJG-RE8Y2It91WL9LctltVrFYW
"""

pip install xmltodict

import requests, xmltodict
import pandas as pd

key = "YIG48RZ4OVNbB15tDMQv6%2FS4eDc38APYyyBkaUCB%2BnrBCbtm7l1hpnNDmVQ1p4RXGoQC7GYdXhpYgoPn%2FIzZww%3D%3D"
url = "http://openapi.tago.go.kr/openapi/service/SuburbsBusInfoService/getSuberbsBusTrminlList?ServiceKey=YIG48RZ4OVNbB15tDMQv6%2FS4eDc38APYyyBkaUCB%2BnrBCbtm7l1hpnNDmVQ1p4RXGoQC7GYdXhpYgoPn%2FIzZww%3D%3D&numOfRows=10000"

content = requests.get(url).content
dict = xmltodict.parse(content)

termIDs, termNms = [], []
suburbs_id_city_name = {}

for terminal in dict['response']['body']['items']['item']:
  city_terminalnm = []
  if len(terminal) < 3:
    continue
  city_terminalnm.append(terminal['cityName'])
  city_terminalnm.append(terminal['terminalNm'])
  suburbs_id_city_name[terminal['terminalId']] = city_terminalnm

df = pd.DataFrame(suburbs_id_city_name)
display(df)
df.to_csv('suburbs_id_city_name.csv')